### ISSUE TITLE
疑问？IPv4/6 优先度

### ISSUE THREAD

**Issue by guaguaya66** [nkeonkeo/MediaUnlockTest#3]
默认参数测试
![image](https://user-images.githubusercontent.com/31442507/201510631-d20aac51-c30d-4095-a371-16a1b05e8d47.png)
使用 `-m 4`  走IPV4测试
![image](https://user-images.githubusercontent.com/31442507/201510593-28606c44-9ff4-4f8b-9c85-65baa2472510.png)

在默认参数测试时，由于机器配置优先IPv6，YouTube解锁全部显示No，但是实际上 IPv4 是解锁的
建议优先使用 IPv4 进行测试，或者分开测试

**Comment by nkeonkeo** [comment]
默认优先级为系统设置

需要测试ipv4用 -m 4 就好了

**Comment by guaguaya66** [comment]
> 

怎么同时测试v4和v6

**Comment by nkeonkeo** [comment]
unlock-test -m 4 && unlock-test -m 6
